name="test"
version="1.0.1"
project="default"
enclave_size="4G"
enclave_lifetime=10
code_location="../../mse-app-demo/helloworld/code"
code_protection="plaintext"
python_flask_module="app"
python_flask_variable_name="app"
health_check_endpoint="/"
