service_name="test"
service_version="1.0.1"
enclave_size="4G"
enclave_lifetime=10
code_location="../../mse-app-demo/helloworld"
code_mode="plaintext"
python_flask_module="app"
python_flask_variable_name="app"
health_check_endpoint="/"