site_name: Microservice Encryption Cloud
site_url: https://docs.cosmian.com/
copyright: © Copyright 2018-2023 Cosmian. All rights reserved
dev_addr: "127.0.0.1:8003"
theme:
  name: "material"
  language: "en"
  font:
    text: Open Sans
  favicon: "favicon.png"
  logo: "https://raw.githubusercontent.com/Cosmian/Files/main/products/cosmian-logo-docs.png"
  custom_dir: overrides
  features:
    - content.tabs.link
markdown_extensions:
  - tables
  - smarty
  - abbr
  - admonition
  - toc:
      permalink: true
      baselevel: 1
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.arithmatex
  - pymdownx.tasklist
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - attr_list
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      macro-file: docs/src/macros.tex
plugins:
  - search
  - kroki
extra_css:
  - css/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js
  - javascripts/extra.js
nav:
  - Overview: overview.md
  - Getting started: getting_started.md
  - App Configuration: configuration.md
  - Command Line:
      - Context: subcommand/context.md
      - Init: subcommand/init.md
      - Deploy: subcommand/deploy.md
      - List: subcommand/list.md
      - Login: subcommand/login.md
      - Logout: subcommand/logout.md
      - Logs: subcommand/logs.md
      - Status: subcommand/status.md
      - Stop: subcommand/stop.md
      - Test: subcommand/test.md
      - Verify: subcommand/verify.md
  - Develop your app: develop.md
  - Usage Scenarios: scenarios.md
  - Security Model: security.md
  - App Deployment Flow: how_it_works_deploy.md
  - App Usage Flow: how_it_works_use.md
