site_name: Cosmian Enclave CLI user manual
site_url: https://docs.cosmian.com/
copyright: © Copyright 2018-2023 Cosmian. All rights reserved
dev_addr: "127.0.0.1:8003"
theme:
  name: "material"
  language: "en"
  font:
    text: Open Sans
  favicon: "favicon.png"
  logo: "https://raw.githubusercontent.com/Cosmian/Files/main/products/cosmian-logo-docs.png"
  custom_dir: theme_overrides
  features:
    - content.tabs.link
markdown_extensions:
  - tables
  - smarty
  - abbr
  - admonition
  - toc:
      permalink: true
      baselevel: 1
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.arithmatex
  - pymdownx.tasklist
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - attr_list
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      macro-file: docs/src/macros.tex
plugins:
  - search
  - kroki
  - meta-descriptions
nav:
#  - Overview: overview.md
  - Bare Metal:
      - Bare Metal - Getting Started: bare-metal/getting_started.md
      - Develop: bare-metal/develop.md
      - Flow: bare-metal/flow.md
      - Command Line:
          - Evidence: bare-metal/subcommand/evidence.md
          - List: bare-metal/subcommand/list.md
          - Logs: bare-metal/subcommand/logs.md
          - Restart: bare-metal/subcommand/restart.md
          - Status: bare-metal/subcommand/status.md
          - Stop: bare-metal/subcommand/stop.md
  - SaaS:
      - SaaS - Getting Started: saas/getting_started.md
      - App Configuration: saas/configuration.md
      - Command Line:
          - Context: saas/subcommand/context.md
          - Init: saas/subcommand/init.md
          - Deploy: saas/subcommand/deploy.md
          - List: saas/subcommand/list.md
          - Localtest: saas/subcommand/localtest.md
          - Login: saas/subcommand/login.md
          - Logout: saas/subcommand/logout.md
          - Logs: saas/subcommand/logs.md
          - Status: saas/subcommand/status.md
          - Stop: saas/subcommand/stop.md
          - Test: saas/subcommand/test.md
          - Verify: saas/subcommand/verify.md
      - Develop your app: saas/develop.md
      - Usage Scenarios: saas/scenarios.md
      - Security Model: saas/security.md
      - App Deployment Flow: saas/how_it_works_deploy.md
      - App Usage Flow: saas/how_it_works_use.md

