site_name: Cosmian Enclave CLI user manual
site_url: https://docs.cosmian.com/
copyright: © Copyright 2018-2023 Cosmian. All rights reserved
dev_addr: "127.0.0.1:8003"
theme:
  name: "material"
  language: "en"
  font:
    text: Open Sans
  favicon: "favicon.png"
  logo: "https://raw.githubusercontent.com/Cosmian/Files/main/products/cosmian-logo-docs.png"
  custom_dir: theme_overrides
  features:
    - content.tabs.link
markdown_extensions:
  - tables
  - smarty
  - abbr
  - admonition
  - toc:
      permalink: true
      baselevel: 1
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.arithmatex
  - pymdownx.tasklist
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - attr_list
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      macro-file: docs/src/macros.tex
plugins:
  - search
  - kroki
  - meta-descriptions
nav:
#  - Overview: overview.md
  - Bare Metal:
      - Bare Metal - Getting Started: home/getting_started.md
      - Develop: home/develop.md
      - Flow: home/flow.md
      - Command Line:
          - Evidence: home/subcommand/evidence.md
          - List: home/subcommand/list.md
          - Logs: home/subcommand/logs.md
          - Restart: home/subcommand/restart.md
          - Status: home/subcommand/status.md
          - Stop: home/subcommand/stop.md
  - Cosmian SaaS:
      - SaaS - Getting Started: cloud/getting_started.md
      - App Configuration: cloud/configuration.md
      - Command Line:
          - Context: cloud/subcommand/context.md
          - Init: cloud/subcommand/init.md
          - Deploy: cloud/subcommand/deploy.md
          - List: cloud/subcommand/list.md
          - Localtest: cloud/subcommand/localtest.md
          - Login: cloud/subcommand/login.md
          - Logout: cloud/subcommand/logout.md
          - Logs: cloud/subcommand/logs.md
          - Status: cloud/subcommand/status.md
          - Stop: cloud/subcommand/stop.md
          - Test: cloud/subcommand/test.md
          - Verify: cloud/subcommand/verify.md
      - Develop your app: cloud/develop.md
      - Usage Scenarios: cloud/scenarios.md
      - Security Model: cloud/security.md
      - App Deployment Flow: cloud/how_it_works_deploy.md
      - App Usage Flow: cloud/how_it_works_use.md

