site_name: Microservice Encryption
site_url: https://docs.cosmian.com/
copyright: © Copyright 2018-2023 Cosmian. All rights reserved
dev_addr: "127.0.0.1:8003"
theme:
  name: "material"
  language: "en"
  font:
    text: Open Sans
  favicon: "favicon.png"
  logo: "images/docslogo-2x.png"
  custom_dir: overrides
  features:
    - content.tabs.link
markdown_extensions:
  - tables
  - smarty
  - abbr
  - admonition
  - toc:
      permalink: true
      baselevel: 1
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.arithmatex
  - pymdownx.tasklist
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - attr_list
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      macro-file: docs/src/macros.tex
plugins:
  - search
  - kroki
extra_css:
  - css/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js
  - javascripts/extra.js
nav:
  - Getting started: microservice_encryption/getting_started.md
  - Scaffold a new project: microservice_encryption/subcommand/scaffold.md
  - Configuration: microservice_encryption/configuration.md
  - Advanced options:
      - Context: microservice_encryption/context.md
      - List: microservice_encryption/subcommand/list.md
      - Remove: microservice_encryption/subcommand/remove.md
      - Status: microservice_encryption/subcommand/status.md
      - Stop: microservice_encryption/subcommand/stop.md
  - About:
      - Scenarii: microservice_encryption/scenarii.md
      - Deployment: microservice_encryption/how_it_works_deploy.md
      - Usage: microservice_encryption/how_it_works_use.md
      - Security explain: microservice_encryption/security.md
  - Python API: microservice_encryption/python/
