name: Test staging environment

on:
  schedule:
    - cron: "00 21 * * *"

jobs:
  tests:
    runs-on: [self-hosted, not-sgx]

    steps:
      # Solve perm denied issue on GA
      # see: https://github.com/actions/checkout/issues/211
      - name: Chown user
        run: |
          echo $USER
          echo $GITHUB_WORKSPACE
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install .

      - name: Run integration tests
        env:
          MSE_BASE_URL: "https://backend.staging.mse.cosmian.com"
          MSE_AUTH0_CLIENT_ID: "Vm94ZbQn7fFpf5IbA6511S8yp3DQeau2"
          MSE_AUTH0_DOMAIN_NAME: "https://mse-console-test.eu.auth0.com"
          MSE_AUTH0_AUDIENCE: "https://mse-console-test.eu.auth0.com/api/v2/"
          REFRESH_TOKEN: ${{ secrets.STAGING_ALICE_REFRESH_TOKEN }}
          MSE_TEST_DOMAIN_NAME: ${{ vars.STAGING_MSE_TEST_DOMAIN_NAME }}
          MSE_TEST_PRIVATE_KEY: ${{ secrets.STAGING_MSE_TEST_PRIVATE_KEY }}
          MSE_TEST_PUBLIC_KEY: ${{ vars.STAGING_MSE_TEST_PUBLIC_KEY }}
          MSE_CONF_PATH: ${{ github.workspace }}
        run: |
          echo 'email = "alice@cosmian.com"' > ${MSE_CONF_PATH}/login.toml
          echo "refresh_token = \"${REFRESH_TOKEN}\"" >> ${MSE_CONF_PATH}/login.toml
          echo "Running tests using ${MSE_BASE_URL}"
          pytest -m cloud
